apiVersion: v1
kind: Service
metadata:
  name: svc-in-nginx
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
  type: NodePort
